/*
 * This source file was generated by the Gradle 'init' task
* Template Used by Jake Anderberg
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!    Goodbye!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
